// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NickFinance.PettyCash;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NickFinance.PettyCash.Migrations
{
    [DbContext(typeof(PettyCashDbContext))]
    [Migration("20260426104734_Initial_PettyCash")]
    partial class Initial_PettyCash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("petty_cash")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NickFinance.PettyCash.Approvals.VoucherApproval", b =>
                {
                    b.Property<Guid>("VoucherApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("voucher_approval_id");

                    b.Property<Guid>("AssignedToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_user_id");

                    b.Property<short>("Decision")
                        .HasColumnType("smallint")
                        .HasColumnName("decision");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.Property<short>("StepNo")
                        .HasColumnType("smallint")
                        .HasColumnName("step_no");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("uuid")
                        .HasColumnName("voucher_id");

                    b.HasKey("VoucherApprovalId");

                    b.HasIndex("VoucherId", "StepNo")
                        .IsUnique()
                        .HasDatabaseName("ux_voucher_approvals_voucher_step");

                    b.HasIndex("TenantId", "AssignedToUserId", "Decision")
                        .HasDatabaseName("ix_voucher_approvals_assignee_decision");

                    b.ToTable("voucher_approvals", "petty_cash");
                });

            modelBuilder.Entity("NickFinance.PettyCash.Float", b =>
                {
                    b.Property<Guid>("FloatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("float_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("CustodianUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("custodian_user_id");

                    b.Property<long>("FloatAmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("float_amount_minor");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<short>("ReplenishThresholdPct")
                        .HasColumnType("smallint")
                        .HasColumnName("replenish_threshold_pct");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("FloatId");

                    b.HasIndex("TenantId", "SiteId", "CurrencyCode", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("ux_floats_active_per_site_currency")
                        .HasFilter("\"is_active\" = TRUE");

                    b.ToTable("floats", "petty_cash");
                });

            modelBuilder.Entity("NickFinance.PettyCash.Voucher", b =>
                {
                    b.Property<Guid>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("voucher_id");

                    b.Property<long?>("AmountApprovedMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_approved_minor");

                    b.Property<long>("AmountRequestedMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_requested_minor");

                    b.Property<short>("Category")
                        .HasColumnType("smallint")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_user_id");

                    b.Property<string>("DecisionComment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("decision_comment");

                    b.Property<DateTimeOffset?>("DisbursedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disbursed_at");

                    b.Property<Guid?>("DisbursedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("disbursed_by_user_id");

                    b.Property<Guid>("FloatId")
                        .HasColumnType("uuid")
                        .HasColumnName("float_id");

                    b.Property<Guid?>("LedgerEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_event_id");

                    b.Property<string>("PayeeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("payee_name");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("project_code");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("purpose");

                    b.Property<Guid>("RequesterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_user_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("VoucherNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("voucher_no");

                    b.HasKey("VoucherId");

                    b.HasIndex("FloatId");

                    b.HasIndex("TenantId", "VoucherNo")
                        .IsUnique()
                        .HasDatabaseName("ux_vouchers_tenant_voucher_no");

                    b.HasIndex("TenantId", "FloatId", "Status")
                        .HasDatabaseName("ix_vouchers_tenant_float_status");

                    b.HasIndex("TenantId", "RequesterUserId", "Status")
                        .HasDatabaseName("ix_vouchers_tenant_requester_status");

                    b.ToTable("vouchers", "petty_cash");
                });

            modelBuilder.Entity("NickFinance.PettyCash.VoucherLineItem", b =>
                {
                    b.Property<Guid>("VoucherLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("voucher_line_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("GlAccount")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("gl_account");

                    b.Property<long>("GrossAmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("gross_amount_minor");

                    b.Property<short>("LineNo")
                        .HasColumnType("smallint")
                        .HasColumnName("line_no");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("uuid")
                        .HasColumnName("voucher_id");

                    b.HasKey("VoucherLineId");

                    b.HasIndex("VoucherId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("ux_voucher_lines_voucher_lineno");

                    b.ToTable("voucher_line_items", "petty_cash");
                });

            modelBuilder.Entity("NickFinance.PettyCash.Approvals.VoucherApproval", b =>
                {
                    b.HasOne("NickFinance.PettyCash.Voucher", null)
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NickFinance.PettyCash.Voucher", b =>
                {
                    b.HasOne("NickFinance.PettyCash.Float", null)
                        .WithMany()
                        .HasForeignKey("FloatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NickFinance.PettyCash.VoucherLineItem", b =>
                {
                    b.HasOne("NickFinance.PettyCash.Voucher", null)
                        .WithMany("Lines")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NickFinance.PettyCash.Voucher", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
