// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NickFinance.AP;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NickFinance.AP.Migrations
{
    [DbContext(typeof(ApDbContext))]
    partial class ApDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ap")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NickFinance.AP.ApBill", b =>
                {
                    b.Property<Guid>("ApBillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("bill_id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<DateOnly>("BillDate")
                        .HasColumnType("date")
                        .HasColumnName("bill_date");

                    b.Property<string>("BillNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("bill_no");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("GrnReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("grn_reference");

                    b.Property<long>("GrossMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("gross_minor");

                    b.Property<Guid?>("LedgerEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_event_id");

                    b.Property<long>("LeviesMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("levies_minor");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<long>("PaidMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("paid_minor");

                    b.Property<string>("PoReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("po_reference");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<long>("SubtotalNetMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("subtotal_net_minor");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<long>("VatMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("vat_minor");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<string>("VendorReference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("vendor_reference");

                    b.Property<long>("WhtMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("wht_minor");

                    b.Property<long>("WhtRateBp")
                        .HasColumnType("bigint")
                        .HasColumnName("wht_rate_bp");

                    b.HasKey("ApBillId");

                    b.HasIndex("VendorId");

                    b.HasIndex("TenantId", "BillNo")
                        .IsUnique()
                        .HasDatabaseName("ux_bills_tenant_billno");

                    b.HasIndex("TenantId", "VendorId", "Status")
                        .HasDatabaseName("ix_bills_tenant_vendor_status");

                    b.ToTable("bills", "ap");
                });

            modelBuilder.Entity("NickFinance.AP.ApBillLine", b =>
                {
                    b.Property<Guid>("ApBillLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("bill_line_id");

                    b.Property<Guid>("ApBillId")
                        .HasColumnType("uuid")
                        .HasColumnName("bill_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("ExpenseAccount")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("expense_account");

                    b.Property<short>("LineNo")
                        .HasColumnType("smallint")
                        .HasColumnName("line_no");

                    b.Property<long>("NetAmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("net_amount_minor");

                    b.HasKey("ApBillLineId");

                    b.HasIndex("ApBillId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("ux_bill_lines_bill_line");

                    b.ToTable("bill_lines", "ap");
                });

            modelBuilder.Entity("NickFinance.AP.ApPayment", b =>
                {
                    b.Property<Guid>("ApPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<Guid>("ApBillId")
                        .HasColumnType("uuid")
                        .HasColumnName("bill_id");

                    b.Property<string>("CashAccount")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cash_account");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<Guid?>("LedgerEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_event_id");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentRail")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("payment_rail");

                    b.Property<Guid>("PaymentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_run_id");

                    b.Property<string>("RailReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("rail_reference");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("ApPaymentId");

                    b.HasIndex("ApBillId");

                    b.HasIndex("TenantId", "PaymentRunId")
                        .HasDatabaseName("ix_payments_tenant_run");

                    b.ToTable("payments", "ap");
                });

            modelBuilder.Entity("NickFinance.AP.Vendor", b =>
                {
                    b.Property<Guid>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("bank_account_number");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bank_name");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultExpenseAccount")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("default_expense_account");

                    b.Property<short>("DefaultWht")
                        .HasColumnType("smallint")
                        .HasColumnName("default_wht");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsVatRegistered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_vat_registered");

                    b.Property<string>("MomoNetwork")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("momo_network");

                    b.Property<string>("MomoNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("momo_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tin")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tin");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("WhtExempt")
                        .HasColumnType("boolean")
                        .HasColumnName("wht_exempt");

                    b.HasKey("VendorId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_vendors_tenant_code");

                    b.ToTable("vendors", "ap");
                });

            modelBuilder.Entity("NickFinance.AP.WhtCertificate", b =>
                {
                    b.Property<Guid>("WhtCertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("wht_certificate_id");

                    b.Property<Guid?>("ApBillId")
                        .HasColumnType("uuid")
                        .HasColumnName("bill_id");

                    b.Property<Guid?>("ApPaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("CertificateNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("certificate_no");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<long>("GrossPaidMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("gross_paid_minor");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<short>("TransactionType")
                        .HasColumnType("smallint")
                        .HasColumnName("transaction_type");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<long>("WhtDeductedMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("wht_deducted_minor");

                    b.Property<decimal>("WhtRate")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("wht_rate");

                    b.HasKey("WhtCertificateId");

                    b.HasIndex("TenantId", "CertificateNo")
                        .IsUnique()
                        .HasDatabaseName("ux_wht_certs_tenant_no");

                    b.HasIndex("TenantId", "VendorId", "IssueDate")
                        .HasDatabaseName("ix_wht_certs_vendor_date");

                    b.ToTable("wht_certificates", "ap");
                });

            modelBuilder.Entity("NickFinance.AP.ApBill", b =>
                {
                    b.HasOne("NickFinance.AP.Vendor", null)
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NickFinance.AP.ApBillLine", b =>
                {
                    b.HasOne("NickFinance.AP.ApBill", null)
                        .WithMany("Lines")
                        .HasForeignKey("ApBillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NickFinance.AP.ApPayment", b =>
                {
                    b.HasOne("NickFinance.AP.ApBill", null)
                        .WithMany()
                        .HasForeignKey("ApBillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NickFinance.AP.ApBill", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
