// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NickFinance.Ledger;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NickFinance.Ledger.Migrations
{
    [DbContext(typeof(LedgerDbContext))]
    partial class LedgerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("finance")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NickFinance.Ledger.AccountingPeriod", b =>
                {
                    b.Property<Guid>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by_user_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<byte>("MonthNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("month_number");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("PeriodId");

                    b.HasIndex("TenantId", "FiscalYear", "MonthNumber")
                        .IsUnique();

                    b.ToTable("accounting_periods", "finance");
                });

            modelBuilder.Entity("NickFinance.Ledger.LedgerEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("committed_at");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("event_type");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Narration")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("narration");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<Guid?>("ReversesEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_event_id");

                    b.Property<string>("SourceEntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_entity_id");

                    b.Property<string>("SourceEntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_entity_type");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_module");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("EventId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("PeriodId");

                    b.HasIndex("ReversesEventId");

                    b.HasIndex("TenantId", "EffectiveDate");

                    b.HasIndex("TenantId", "PeriodId");

                    b.ToTable("ledger_events", "finance");
                });

            modelBuilder.Entity("NickFinance.Ledger.LedgerEventLine", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<short>("LineNo")
                        .HasColumnType("smallint")
                        .HasColumnName("line_no");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_code");

                    b.Property<string>("CostCenterCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cost_center_code");

                    b.Property<long>("CreditMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("credit_minor");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<long>("DebitMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("debit_minor");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("DimsExtraJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("dims_extra");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("project_code");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.HasKey("EventId", "LineNo");

                    b.HasIndex("SiteId");

                    b.HasIndex("AccountCode", "CurrencyCode");

                    b.ToTable("ledger_event_lines", "finance");
                });

            modelBuilder.Entity("NickFinance.Ledger.LedgerEvent", b =>
                {
                    b.HasOne("NickFinance.Ledger.AccountingPeriod", null)
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NickFinance.Ledger.LedgerEventLine", b =>
                {
                    b.HasOne("NickFinance.Ledger.LedgerEvent", "Event")
                        .WithMany("Lines")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("NickFinance.Ledger.LedgerEvent", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
