// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NickFinance.Banking;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NickFinance.Banking.Migrations
{
    [DbContext(typeof(BankingDbContext))]
    [Migration("20260429124632_Add_FxRevaluationLog")]
    partial class Add_FxRevaluationLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("banking")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NickFinance.Banking.BankAccount", b =>
                {
                    b.Property<Guid>("BankAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("bank_account_id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_number");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bank_name");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LedgerAccount")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ledger_account");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("BankAccountId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_bank_accounts_tenant_code");

                    b.ToTable("bank_accounts", "banking");
                });

            modelBuilder.Entity("NickFinance.Banking.BankStatement", b =>
                {
                    b.Property<Guid>("BankStatementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("statement_id");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_account_id");

                    b.Property<long>("ClosingBalanceMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("closing_balance_minor");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<Guid>("ImportedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("imported_by_user_id");

                    b.Property<long>("OpeningBalanceMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("opening_balance_minor");

                    b.Property<string>("ParserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("parser_name");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_file_name");

                    b.Property<DateOnly>("StatementDate")
                        .HasColumnType("date")
                        .HasColumnName("statement_date");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("BankStatementId");

                    b.HasIndex("BankAccountId", "PeriodStart", "PeriodEnd")
                        .HasDatabaseName("ix_statements_account_period");

                    b.ToTable("statements", "banking");
                });

            modelBuilder.Entity("NickFinance.Banking.BankTransaction", b =>
                {
                    b.Property<Guid>("BankTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_account_id");

                    b.Property<Guid>("BankStatementId")
                        .HasColumnType("uuid")
                        .HasColumnName("statement_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<short>("Direction")
                        .HasColumnType("smallint")
                        .HasColumnName("direction");

                    b.Property<short>("MatchStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("match_status");

                    b.Property<DateTimeOffset?>("MatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("matched_at");

                    b.Property<Guid?>("MatchedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("matched_by_user_id");

                    b.Property<Guid?>("MatchedToEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("matched_to_entity_id");

                    b.Property<string>("MatchedToEntityType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("matched_to_entity_type");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.Property<DateOnly?>("ValueDate")
                        .HasColumnType("date")
                        .HasColumnName("value_date");

                    b.HasKey("BankTransactionId");

                    b.HasIndex("BankStatementId");

                    b.HasIndex("BankAccountId", "TransactionDate")
                        .HasDatabaseName("ix_transactions_account_date");

                    b.HasIndex("TenantId", "MatchStatus")
                        .HasDatabaseName("ix_transactions_tenant_status");

                    b.ToTable("transactions", "banking");
                });

            modelBuilder.Entity("NickFinance.Banking.FxRate", b =>
                {
                    b.Property<Guid>("FxRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("fx_rate_id");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("as_of_date");

                    b.Property<string>("FromCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("from_currency");

                    b.Property<string>("ProviderPayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("provider_payload_json");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("rate");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ToCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("to_currency");

                    b.HasKey("FxRateId");

                    b.HasIndex("TenantId", "FromCurrency", "ToCurrency", "AsOfDate")
                        .IsUnique()
                        .HasDatabaseName("ux_fx_rates_tenant_pair_date");

                    b.HasIndex("TenantId", "FromCurrency", "ToCurrency", "AsOfDate", "Rate")
                        .HasDatabaseName("ix_fx_rates_lookup");

                    b.ToTable("fx_rates", "banking");
                });

            modelBuilder.Entity("NickFinance.Banking.FxRevaluationLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("log_id");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("as_of_date");

                    b.Property<long>("BalanceMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_minor");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("GlAccount")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("gl_account");

                    b.Property<Guid>("LedgerEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_event_id");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<decimal>("RateUsed")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("rate_used");

                    b.Property<DateTimeOffset>("RevaluedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revalued_at");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("LogId");

                    b.HasIndex("TenantId", "GlAccount", "CurrencyCode", "AsOfDate")
                        .HasDatabaseName("ix_fx_revaluation_log_lookup");

                    b.HasIndex("TenantId", "GlAccount", "CurrencyCode", "PeriodId")
                        .IsUnique()
                        .HasDatabaseName("ux_fx_revaluation_log_tenant_account_ccy_period");

                    b.ToTable("fx_revaluation_log", "banking");
                });

            modelBuilder.Entity("NickFinance.Banking.ReconciliationSession", b =>
                {
                    b.Property<Guid>("ReconciliationSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("reconciliation_id");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("as_of_date");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_account_id");

                    b.Property<long>("BankBalanceMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("bank_balance_minor");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by_user_id");

                    b.Property<long>("LedgerBalanceMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("ledger_balance_minor");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid>("OpenedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("opened_by_user_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("ReconciliationSessionId");

                    b.HasIndex("BankAccountId", "AsOfDate")
                        .HasDatabaseName("ix_reconciliations_account_date");

                    b.ToTable("reconciliations", "banking");
                });

            modelBuilder.Entity("NickFinance.Banking.BankStatement", b =>
                {
                    b.HasOne("NickFinance.Banking.BankAccount", null)
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NickFinance.Banking.BankTransaction", b =>
                {
                    b.HasOne("NickFinance.Banking.BankStatement", null)
                        .WithMany()
                        .HasForeignKey("BankStatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
