// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NickFinance.FixedAssets;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NickFinance.FixedAssets.Migrations
{
    [DbContext(typeof(FixedAssetsDbContext))]
    [Migration("20260426174737_Initial_FixedAssets")]
    partial class Initial_FixedAssets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fixed_assets")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NickFinance.FixedAssets.FixedAsset", b =>
                {
                    b.Property<Guid>("FixedAssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("AccumulatedDepreciationAccount")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("accumulated_depreciation_account");

                    b.Property<long>("AccumulatedDepreciationMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("accumulated_depreciation_minor");

                    b.Property<DateOnly>("AcquiredOn")
                        .HasColumnType("date")
                        .HasColumnName("acquired_on");

                    b.Property<long>("AcquisitionCostMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("acquisition_cost_minor");

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("asset_tag");

                    b.Property<short>("Category")
                        .HasColumnType("smallint")
                        .HasColumnName("category");

                    b.Property<string>("CostAccount")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cost_account");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<decimal>("DecliningBalanceRate")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("declining_balance_rate");

                    b.Property<string>("DepreciationExpenseAccount")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("depreciation_expense_account");

                    b.Property<long?>("DisposalProceedsMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("disposal_proceeds_minor");

                    b.Property<DateOnly?>("DisposedOn")
                        .HasColumnType("date")
                        .HasColumnName("disposed_on");

                    b.Property<DateOnly?>("LastDepreciatedThrough")
                        .HasColumnType("date")
                        .HasColumnName("last_depreciated_through");

                    b.Property<short>("Method")
                        .HasColumnType("smallint")
                        .HasColumnName("method");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<long>("SalvageValueMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("salvage_value_minor");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UsefulLifeMonths")
                        .HasColumnType("integer")
                        .HasColumnName("useful_life_months");

                    b.HasKey("FixedAssetId");

                    b.HasIndex("TenantId", "AssetTag")
                        .IsUnique()
                        .HasDatabaseName("ux_assets_tenant_tag");

                    b.HasIndex("TenantId", "Status", "Category")
                        .HasDatabaseName("ix_assets_tenant_status_cat");

                    b.ToTable("assets", "fixed_assets");
                });
#pragma warning restore 612, 618
        }
    }
}
