// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using NickScanCentralImagingPortal.Infrastructure.Data;

#nullable disable

namespace NickScanCentralImagingPortal.Infrastructure.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260516213000_AddScanImageIdentity")]
    partial class AddScanImageIdentity
    {
    }
}
