// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using NickScanCentralImagingPortal.Infrastructure.Data;

#nullable disable

namespace NickScanCentralImagingPortal.Infrastructure.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260517150000_AddCameraEvidenceTables")]
    partial class AddCameraEvidenceTables
    {
    }
}
