using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NickScanCentralImagingPortal.Infrastructure.Migrations.Application
{
    /// <inheritdoc />
    public partial class BaselineWaveProcessing : Migration
    {
        /// <inheritdoc />
        /// <remarks>
        /// SNAPSHOT RECONCILIATION MIGRATION.
        ///
        /// Wave processing schema (AnalysisParentGroups, WavePendingContainers, wave
        /// columns on AnalysisGroups / AnalysisSettings, and the AiCargoSummary column
        /// on AnalysisGroups) was applied to the live nickscan_production database by
        /// hand (see Migrations/wave_processing_schema.sql) without a corresponding EF
        /// migration, so ApplicationDbContextModelSnapshot.cs drifted from the model.
        ///
        /// The EF scaffold also wanted to DROP icumcontainerdata / icummanifestitems —
        /// those tables were removed from the C# entity model but still exist in the
        /// live DB. We intentionally do NOT drop them here.
        ///
        /// This migration's Up() is therefore an idempotent baseline: every DDL is
        /// guarded by IF NOT EXISTS so running it against the already-migrated live
        /// database is a no-op, while running it against a fresh database will create
        /// the wave-processing schema. Down() is intentionally empty — we never want
        /// to undo live production schema from a snapshot-reconciliation migration.
        ///
        /// The real purpose of this file is the accompanying snapshot update; Up()
        /// just has to be safe in both directions.
        /// </remarks>
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 1. AnalysisParentGroups table
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS analysisparentgroups (
                    id uuid NOT NULL,
                    groupidentifier character varying(150) NOT NULL,
                    scannertype character varying(20) NULL,
                    totalexpectedcontainers integer NOT NULL DEFAULT 0,
                    completedwavecount integer NOT NULL DEFAULT 0,
                    status character varying(20) NOT NULL DEFAULT 'Active',
                    autoclosedate timestamp with time zone NULL,
                    createdatutc timestamp with time zone NOT NULL DEFAULT NOW(),
                    updatedatutc timestamp with time zone NULL,
                    CONSTRAINT pk_analysisparentgroups PRIMARY KEY (id)
                );
            ");

            // Columns the hand-applied SQL may not have created (newer EF model)
            migrationBuilder.Sql("ALTER TABLE analysisparentgroups ADD COLUMN IF NOT EXISTS completedwavecount integer NOT NULL DEFAULT 0;");
            migrationBuilder.Sql("ALTER TABLE analysisparentgroups ADD COLUMN IF NOT EXISTS autoclosedate timestamp with time zone NULL;");
            migrationBuilder.Sql("ALTER TABLE analysisparentgroups ADD COLUMN IF NOT EXISTS updatedatutc timestamp with time zone NULL;");

            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS ix_analysisparentgroups_status ON analysisparentgroups(status);");

            // 2. WavePendingContainers table
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS wavependingcontainers (
                    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    parentgroupid uuid NOT NULL,
                    containernumber character varying(50) NOT NULL,
                    scannertype character varying(20) NULL,
                    firstseenutc timestamp with time zone NOT NULL DEFAULT NOW(),
                    becamereadyutc timestamp with time zone NULL,
                    assignedtowaveid uuid NULL,
                    status character varying(20) NOT NULL DEFAULT 'Pending',
                    CONSTRAINT pk_wavependingcontainers PRIMARY KEY (id)
                );
            ");

            migrationBuilder.Sql("ALTER TABLE wavependingcontainers ADD COLUMN IF NOT EXISTS assignedtowaveid uuid NULL;");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS ix_wavependingcontainers_parentgroupid ON wavependingcontainers(parentgroupid);");

            // 3. AnalysisGroups wave columns + AiCargoSummary
            migrationBuilder.Sql("ALTER TABLE analysisgroups ADD COLUMN IF NOT EXISTS parentgroupid uuid NULL;");
            migrationBuilder.Sql("ALTER TABLE analysisgroups ADD COLUMN IF NOT EXISTS wavenumber integer NULL;");
            migrationBuilder.Sql("ALTER TABLE analysisgroups ADD COLUMN IF NOT EXISTS wavecreatedreason character varying(50) NULL;");
            migrationBuilder.Sql("ALTER TABLE analysisgroups ADD COLUMN IF NOT EXISTS aicargosummary character varying(2000) NULL;");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS ix_analysisgroups_parentgroupid ON analysisgroups(parentgroupid);");

            // 4. AnalysisSettings wave columns
            migrationBuilder.Sql("ALTER TABLE analysissettings ADD COLUMN IF NOT EXISTS enablewaveprocessing boolean NOT NULL DEFAULT false;");
            migrationBuilder.Sql("ALTER TABLE analysissettings ADD COLUMN IF NOT EXISTS waveminbatchsize integer NOT NULL DEFAULT 3;");
            migrationBuilder.Sql("ALTER TABLE analysissettings ADD COLUMN IF NOT EXISTS wavetimeouthours integer NOT NULL DEFAULT 24;");
            migrationBuilder.Sql("ALTER TABLE analysissettings ADD COLUMN IF NOT EXISTS waveautoclosedays integer NOT NULL DEFAULT 30;");

            // NOTE: EF's scaffold also wanted to DropTable icumcontainerdata and
            // icummanifestitems. We intentionally omit those drops — those tables
            // still exist in the live database and dropping them would be destructive.
            // The C# entity model no longer references them; that is acceptable
            // orphaning until a deliberate future migration cleans them up.
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Intentionally empty. This migration is a snapshot-reconciliation
            // baseline; reverting it must never drop production data.
        }
    }
}
