// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using NickScanCentralImagingPortal.Infrastructure.Data;

#nullable disable

namespace NickScanCentralImagingPortal.Infrastructure.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260514193000_AddEagleA25ScannerTables")]
    partial class AddEagleA25ScannerTables
    {
    }
}
