// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NickScanCentralImagingPortal.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NickScanCentralImagingPortal.Infrastructure.Migrations.IcumDownloadsDb
{
    [DbContext(typeof(IcumDownloadsDbContext))]
    partial class IcumDownloadsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NickScanCentralImagingPortal.Core.Entities.CMRRedownloadQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContainerNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("containernumber");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("errormessage");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer")
                        .HasColumnName("maxretries");

                    b.Property<string>("OriginalClearanceType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("originalclearancetype");

                    b.Property<string>("OriginalDeclarationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("originaldeclarationnumber");

                    b.Property<string>("Priority")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processedat");

                    b.Property<string>("ProcessedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("processedby");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queuedat");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retrycount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_cmrredownloadqueue");

                    b.HasIndex("ContainerNumber")
                        .HasDatabaseName("ix_cmrredownloadqueue_containernumber");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_cmrredownloadqueue_processedat");

                    b.HasIndex("QueuedAt")
                        .HasDatabaseName("ix_cmrredownloadqueue_queuedat");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_cmrredownloadqueue_status");

                    b.HasIndex("Status", "Priority", "QueuedAt")
                        .HasDatabaseName("ix_cmrredownloadqueue_statuspriorityqueued");

                    b.ToTable("cmrredownloadqueue");
                });

            modelBuilder.Entity("NickScanCentralImagingPortal.Core.Entities.CMRValidationMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageRedownloadTimeMinutes")
                        .HasColumnType("double precision")
                        .HasColumnName("averageredownloadtimeminutes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<int>("FixedRecordsToday")
                        .HasColumnType("integer")
                        .HasColumnName("fixedrecordstoday");

                    b.Property<int>("InvalidCMRRecords")
                        .HasColumnType("integer")
                        .HasColumnName("invalidcmrrecords");

                    b.Property<int>("MissingBlNumber")
                        .HasColumnType("integer")
                        .HasColumnName("missingblnumber");

                    b.Property<int>("MissingBothFields")
                        .HasColumnType("integer")
                        .HasColumnName("missingbothfields");

                    b.Property<int>("MissingRotationNumber")
                        .HasColumnType("integer")
                        .HasColumnName("missingrotationnumber");

                    b.Property<int>("NewIssuesDetectedToday")
                        .HasColumnType("integer")
                        .HasColumnName("newissuesdetectedtoday");

                    b.Property<int>("NewRecordsToday")
                        .HasColumnType("integer")
                        .HasColumnName("newrecordstoday");

                    b.Property<int>("QueueCompletedCount")
                        .HasColumnType("integer")
                        .HasColumnName("queuecompletedcount");

                    b.Property<int>("QueueFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("queuefailedcount");

                    b.Property<int>("QueuePendingCount")
                        .HasColumnType("integer")
                        .HasColumnName("queuependingcount");

                    b.Property<int>("QueueProcessingCount")
                        .HasColumnType("integer")
                        .HasColumnName("queueprocessingcount");

                    b.Property<double>("QueueSuccessRate")
                        .HasColumnType("double precision")
                        .HasColumnName("queuesuccessrate");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recordedat");

                    b.Property<int>("TotalCMRRecords")
                        .HasColumnType("integer")
                        .HasColumnName("totalcmrrecords");

                    b.Property<int>("ValidCMRRecords")
                        .HasColumnType("integer")
                        .HasColumnName("validcmrrecords");

                    b.Property<double>("ValidationSuccessRate")
                        .HasColumnType("double precision")
                        .HasColumnName("validationsuccessrate");

                    b.HasKey("Id")
                        .HasName("pk_cmrvalidationmetrics");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_cmrvalidationmetrics_createdat");

                    b.HasIndex("RecordedAt")
                        .HasDatabaseName("ix_cmrvalidationmetrics_recordedat");

                    b.ToTable("cmrvalidationmetrics");
                });

            modelBuilder.Entity("NickScanCentralImagingPortal.Core.Entities.ICUMSDownloadQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completedat");

                    b.Property<string>("ContainerNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("containernumber");

                    b.Property<DateTime?>("FirstAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("firstattemptat");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastattemptat");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lasterrorcode");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("lasterrormessage");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer")
                        .HasColumnName("maxretries");

                    b.Property<string>("Metadata")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("metadata");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queuedat");

                    b.Property<string>("RequestSource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("requestsource");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("requestedby");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retrycount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_icumsdownloadqueue");

                    b.HasIndex("CompletedAt")
                        .HasDatabaseName("ix_icumsdownloadqueue_completedat");

                    b.HasIndex("ContainerNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_icumsdownloadqueue_containernumber");

                    b.HasIndex("QueuedAt")
                        .HasDatabaseName("ix_icumsdownloadqueue_queuedat");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_icumsdownloadqueue_status");

                    b.HasIndex("Status", "Priority", "QueuedAt")
                        .HasDatabaseName("ix_icumsdownloadqueue_statuspriorityqueued");

                    b.ToTable("icumsdownloadqueue");
                });

            modelBuilder.Entity("NickScanCentralImagingPortal.Core.Models.ArchivedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchiveDirectory")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("archivedirectory");

                    b.Property<string>("ArchiveFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("archivefilename");

                    b.Property<string>("ArchiveFilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("archivefilepath");

                    b.Property<DateTime>("ArchivedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archiveddate");

                    b.Property<long>("ArchivedSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("archivedsizebytes");

                    b.Property<double>("CompressionRatio")
                        .HasColumnType("double precision")
                        .HasColumnName("compressionratio");

                    b.Property<string>("CompressionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("compressiontype");

                    b.Property<string>("ContainerNumbers")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("containernumbers");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<int>("DocumentCount")
                        .HasColumnType("integer")
                        .HasColumnName("documentcount");

                    b.Property<int>("DownloadedFileId")
                        .HasColumnType("integer")
                        .HasColumnName("downloadedfileid");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("filetype");

                    b.Property<bool>("IsRestored")
                        .HasColumnType("boolean")
                        .HasColumnName("isrestored");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("originalfilename");

                    b.Property<string>("OriginalFilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("originalfilepath");

                    b.Property<long>("OriginalSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("originalsizebytes");

                    b.Property<DateTime>("ProcessedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processeddate");

                    b.Property<DateTime?>("RestoredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("restoreddate");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_archivedfiles");

                    b.HasIndex("ArchivedDate")
                        .HasDatabaseName("ix_archivedfiles_archiveddate");

                    b.HasIndex("DownloadedFileId")
                        .HasDatabaseName("ix_archivedfiles_downloadedfileid");

                    b.HasIndex("FileType")
                        .HasDatabaseName("ix_archivedfiles_filetype");

                    b.HasIndex("IsRestored")
                        .HasDatabaseName("ix_archivedfiles_isrestored");

                    b.HasIndex("ProcessedDate")
                        .HasDatabaseName("ix_archivedfiles_processeddate");

                    b.HasIndex("ArchivedDate", "FileType")
                        .HasDatabaseName("ix_archivedfile_archiveddate_filetype");

                    b.ToTable("archivedfiles");
                });

            modelBuilder.Entity("NickScanCentralImagingPortal.Core.Models.BOEDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BlNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("blnumber");

                    b.Property<string>("CcvrIntelRemarks")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("ccvrintelremarks");

                    b.Property<string>("ClearanceType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clearancetype");

                    b.Property<DateTime?>("CmrUpgradedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cmrupgradedat");

                    b.Property<string>("CompOffRemarks")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("compoffremarks");

                    b.Property<string>("ConsigneeAddress")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("consigneeaddress");

                    b.Property<string>("ConsigneeName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("consigneename");

                    b.Property<string>("ContainerDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("containerdescription");

                    b.Property<string>("ContainerISO")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("containeriso");

                    b.Property<string>("ContainerNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("containernumber");

                    b.Property<int?>("ContainerQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("containerquantity");

                    b.Property<string>("ContainerRemarks")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("containerremarks");

                    b.Property<string>("ContainerSize")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("containersize");

                    b.Property<string>("ContainerStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("containerstatus");

                    b.Property<decimal?>("ContainerWeight")
                        .HasColumnType("numeric")
                        .HasColumnName("containerweight");

                    b.Property<string>("CountryOfOrigin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("countryoforigin");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CrmsLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("crmslevel");

                    b.Property<string>("DeclarantAddress")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("declarantaddress");

                    b.Property<string>("DeclarantName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("declarantname");

                    b.Property<string>("DeclarationDate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("declarationdate");

                    b.Property<string>("DeclarationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("declarationnumber");

                    b.Property<int?>("DeclarationVersion")
                        .HasColumnType("integer")
                        .HasColumnName("declarationversion");

                    b.Property<string>("DeliveryPlace")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("deliveryplace");

                    b.Property<int>("DocumentIndex")
                        .HasColumnType("integer")
                        .HasColumnName("documentindex");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("documenttype");

                    b.Property<int>("DownloadedFileId")
                        .HasColumnType("integer")
                        .HasColumnName("downloadedfileid");

                    b.Property<string>("DriverLicense")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("driverlicense");

                    b.Property<string>("DriverName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("drivername");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("errormessage");

                    b.Property<string>("ExpAddress")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("expaddress");

                    b.Property<string>("ExpName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("expname");

                    b.Property<string>("GoodsDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("goodsdescription");

                    b.Property<bool>("HasIngestionWarnings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("hasingestionwarnings");

                    b.Property<string>("HouseBl")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("housebl");

                    b.Property<string>("ImpAddress")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("impaddress");

                    b.Property<string>("ImpExpAddress")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("impexpaddress");

                    b.Property<string>("ImpExpName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("impexpname");

                    b.Property<string>("ImpName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("impname");

                    b.Property<string>("IngestionWarnings")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("ingestionwarnings");

                    b.Property<bool>("IsConsolidated")
                        .HasColumnType("boolean")
                        .HasColumnName("isconsolidated");

                    b.Property<string>("MarksNumbers")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("marksnumbers");

                    b.Property<string>("MasterBlNumber")
                        .HasColumnType("text")
                        .HasColumnName("masterblnumber");

                    b.Property<int?>("NoOfContainers")
                        .HasColumnType("integer")
                        .HasColumnName("noofcontainers");

                    b.Property<string>("OriginalClearanceType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("originalclearancetype");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processedat");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("processingstatus");

                    b.Property<string>("RawJsonData")
                        .HasColumnType("text")
                        .HasColumnName("rawjsondata");

                    b.Property<string>("RegimeCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("regimecode");

                    b.Property<string>("RotationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rotationnumber");

                    b.Property<string>("SealNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sealnumber");

                    b.Property<string>("ShipperAddress")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("shipperaddress");

                    b.Property<string>("ShipperName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("shippername");

                    b.Property<decimal?>("TotalDutyPaid")
                        .HasColumnType("numeric")
                        .HasColumnName("totaldutypaid");

                    b.Property<string>("TruckPlateNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("truckplatenumber");

                    b.Property<string>("UnmappedField10Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield10label");

                    b.Property<string>("UnmappedField10Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield10value");

                    b.Property<string>("UnmappedField11Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield11label");

                    b.Property<string>("UnmappedField11Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield11value");

                    b.Property<string>("UnmappedField12Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield12label");

                    b.Property<string>("UnmappedField12Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield12value");

                    b.Property<string>("UnmappedField13Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield13label");

                    b.Property<string>("UnmappedField13Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield13value");

                    b.Property<string>("UnmappedField14Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield14label");

                    b.Property<string>("UnmappedField14Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield14value");

                    b.Property<string>("UnmappedField15Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield15label");

                    b.Property<string>("UnmappedField15Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield15value");

                    b.Property<string>("UnmappedField16Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield16label");

                    b.Property<string>("UnmappedField16Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield16value");

                    b.Property<string>("UnmappedField17Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield17label");

                    b.Property<string>("UnmappedField17Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield17value");

                    b.Property<string>("UnmappedField18Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield18label");

                    b.Property<string>("UnmappedField18Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield18value");

                    b.Property<string>("UnmappedField19Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield19label");

                    b.Property<string>("UnmappedField19Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield19value");

                    b.Property<string>("UnmappedField1Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield1label");

                    b.Property<string>("UnmappedField1Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield1value");

                    b.Property<string>("UnmappedField20Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield20label");

                    b.Property<string>("UnmappedField20Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield20value");

                    b.Property<string>("UnmappedField2Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield2label");

                    b.Property<string>("UnmappedField2Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield2value");

                    b.Property<string>("UnmappedField3Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield3label");

                    b.Property<string>("UnmappedField3Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield3value");

                    b.Property<string>("UnmappedField4Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield4label");

                    b.Property<string>("UnmappedField4Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield4value");

                    b.Property<string>("UnmappedField5Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield5label");

                    b.Property<string>("UnmappedField5Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield5value");

                    b.Property<string>("UnmappedField6Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield6label");

                    b.Property<string>("UnmappedField6Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield6value");

                    b.Property<string>("UnmappedField7Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield7label");

                    b.Property<string>("UnmappedField7Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield7value");

                    b.Property<string>("UnmappedField8Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield8label");

                    b.Property<string>("UnmappedField8Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield8value");

                    b.Property<string>("UnmappedField9Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield9label");

                    b.Property<string>("UnmappedField9Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield9value");

                    b.Property<int?>("UnmappedFieldsCount")
                        .HasColumnType("integer")
                        .HasColumnName("unmappedfieldscount");

                    b.Property<bool>("UnmappedFieldsOverflow")
                        .HasColumnType("boolean")
                        .HasColumnName("unmappedfieldsoverflow");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_boedocuments");

                    b.HasIndex("ContainerNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_boedocument_container_unique_when_declaration_null")
                        .HasFilter("declarationnumber IS NULL");

                    b.HasIndex("DeclarationNumber")
                        .HasDatabaseName("ix_boedocuments_declarationnumber");

                    b.HasIndex("DocumentType")
                        .HasDatabaseName("ix_boedocuments_documenttype");

                    b.HasIndex("DownloadedFileId")
                        .HasDatabaseName("ix_boedocuments_downloadedfileid");

                    b.HasIndex("HasIngestionWarnings")
                        .HasDatabaseName("ix_boedocument_hasingestionwarnings")
                        .HasFilter("\"HasIngestionWarnings\" = true");

                    b.HasIndex("ProcessingStatus")
                        .HasDatabaseName("ix_boedocuments_processingstatus");

                    b.HasIndex("ContainerNumber", "DeclarationNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_boedocument_containernumber_declarationnumber_unique");

                    b.ToTable("boedocuments");
                });

            modelBuilder.Entity("NickScanCentralImagingPortal.Core.Models.ContainerDownloadHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContainerNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("containernumber");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("DownloadSource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("downloadsource");

                    b.Property<DateTime>("DownloadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("downloadedat");

                    b.Property<int?>("DownloadedFileId")
                        .HasColumnType("integer")
                        .HasColumnName("downloadedfileid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("errormessage");

                    b.Property<bool>("HasValidData")
                        .HasColumnType("boolean")
                        .HasColumnName("hasvaliddata");

                    b.HasKey("Id")
                        .HasName("pk_containerdownloadhistory");

                    b.HasIndex("ContainerNumber")
                        .HasDatabaseName("ix_containerdownloadhistory_containernumber");

                    b.HasIndex("DownloadedAt")
                        .HasDatabaseName("ix_containerdownloadhistory_downloadedat");

                    b.HasIndex("HasValidData")
                        .HasDatabaseName("ix_containerdownloadhistory_hasvaliddata");

                    b.HasIndex("ContainerNumber", "DownloadedAt")
                        .HasDatabaseName("ix_containerdownloadhistory_containernumber_downloadedat");

                    b.ToTable("containerdownloadhistory");
                });

            modelBuilder.Entity("NickScanCentralImagingPortal.Core.Models.DownloadedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AverageAccuracyPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("averageaccuracypercent");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<DateTime>("DownloadDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("downloaddate");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("errormessage");

                    b.Property<string>("FileHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("filehash");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("filename");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("filepath");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("filesize");

                    b.Property<string>("LowestAccuracyContainer")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lowestaccuracycontainer");

                    b.Property<double?>("LowestAccuracyPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("lowestaccuracypercent");

                    b.Property<int?>("PartialDocumentCount")
                        .HasColumnType("integer")
                        .HasColumnName("partialdocumentcount");

                    b.Property<int?>("PerfectDocumentCount")
                        .HasColumnType("integer")
                        .HasColumnName("perfectdocumentcount");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processeddate");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("processingstatus");

                    b.Property<int?>("RecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("recordcount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("VerificationDetails")
                        .HasColumnType("text")
                        .HasColumnName("verificationdetails");

                    b.Property<int?>("VerifiedDocumentCount")
                        .HasColumnType("integer")
                        .HasColumnName("verifieddocumentcount");

                    b.HasKey("Id")
                        .HasName("pk_downloadedfiles");

                    b.HasIndex("DownloadDate")
                        .HasDatabaseName("ix_downloadedfiles_downloaddate");

                    b.HasIndex("FileHash")
                        .HasDatabaseName("ix_downloadedfiles_filehash");

                    b.HasIndex("FileName")
                        .HasDatabaseName("ix_downloadedfiles_filename");

                    b.HasIndex("ProcessingStatus")
                        .HasDatabaseName("ix_downloadedfiles_processingstatus");

                    b.ToTable("downloadedfiles");
                });

            modelBuilder.Entity("NickScanCentralImagingPortal.Core.Models.DownloadedManifestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BOEDocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("boedocumentid");

                    b.Property<string>("CountryOfOrigin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("countryoforigin");

                    b.Property<string>("Cpc")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cpc");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("errormessage");

                    b.Property<string>("FobCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("fobcurrency");

                    b.Property<string>("HsCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("hscode");

                    b.Property<decimal?>("ItemDutyPaid")
                        .HasColumnType("numeric")
                        .HasColumnName("itemdutypaid");

                    b.Property<decimal?>("ItemFob")
                        .HasColumnType("numeric")
                        .HasColumnName("itemfob");

                    b.Property<int>("ItemIndex")
                        .HasColumnType("integer")
                        .HasColumnName("itemindex");

                    b.Property<int?>("ItemNo")
                        .HasColumnType("integer")
                        .HasColumnName("itemno");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processedat");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("processingstatus");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<string>("RawJsonData")
                        .HasColumnType("text")
                        .HasColumnName("rawjsondata");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<string>("UnmappedField10Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield10label");

                    b.Property<string>("UnmappedField10Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield10value");

                    b.Property<string>("UnmappedField11Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield11label");

                    b.Property<string>("UnmappedField11Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield11value");

                    b.Property<string>("UnmappedField12Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield12label");

                    b.Property<string>("UnmappedField12Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield12value");

                    b.Property<string>("UnmappedField13Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield13label");

                    b.Property<string>("UnmappedField13Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield13value");

                    b.Property<string>("UnmappedField14Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield14label");

                    b.Property<string>("UnmappedField14Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield14value");

                    b.Property<string>("UnmappedField15Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield15label");

                    b.Property<string>("UnmappedField15Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield15value");

                    b.Property<string>("UnmappedField16Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield16label");

                    b.Property<string>("UnmappedField16Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield16value");

                    b.Property<string>("UnmappedField17Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield17label");

                    b.Property<string>("UnmappedField17Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield17value");

                    b.Property<string>("UnmappedField18Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield18label");

                    b.Property<string>("UnmappedField18Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield18value");

                    b.Property<string>("UnmappedField19Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield19label");

                    b.Property<string>("UnmappedField19Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield19value");

                    b.Property<string>("UnmappedField1Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield1label");

                    b.Property<string>("UnmappedField1Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield1value");

                    b.Property<string>("UnmappedField20Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield20label");

                    b.Property<string>("UnmappedField20Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield20value");

                    b.Property<string>("UnmappedField2Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield2label");

                    b.Property<string>("UnmappedField2Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield2value");

                    b.Property<string>("UnmappedField3Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield3label");

                    b.Property<string>("UnmappedField3Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield3value");

                    b.Property<string>("UnmappedField4Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield4label");

                    b.Property<string>("UnmappedField4Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield4value");

                    b.Property<string>("UnmappedField5Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield5label");

                    b.Property<string>("UnmappedField5Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield5value");

                    b.Property<string>("UnmappedField6Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield6label");

                    b.Property<string>("UnmappedField6Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield6value");

                    b.Property<string>("UnmappedField7Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield7label");

                    b.Property<string>("UnmappedField7Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield7value");

                    b.Property<string>("UnmappedField8Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield8label");

                    b.Property<string>("UnmappedField8Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield8value");

                    b.Property<string>("UnmappedField9Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unmappedfield9label");

                    b.Property<string>("UnmappedField9Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("unmappedfield9value");

                    b.Property<int?>("UnmappedFieldsCount")
                        .HasColumnType("integer")
                        .HasColumnName("unmappedfieldscount");

                    b.Property<bool>("UnmappedFieldsOverflow")
                        .HasColumnType("boolean")
                        .HasColumnName("unmappedfieldsoverflow");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_manifestitems");

                    b.HasIndex("BOEDocumentId")
                        .HasDatabaseName("ix_manifestitems_boedocumentid");

                    b.HasIndex("HsCode")
                        .HasDatabaseName("ix_manifestitems_hscode");

                    b.HasIndex("ProcessingStatus")
                        .HasDatabaseName("ix_manifestitems_processingstatus");

                    b.ToTable("manifestitems");
                });

            modelBuilder.Entity("NickScanCentralImagingPortal.Core.Models.FailedProcessingQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<int>("DownloadedFileId")
                        .HasColumnType("integer")
                        .HasColumnName("downloadedfileid");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("errordetails");

                    b.Property<DateTime>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failedat");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failurereason");

                    b.Property<string>("FailureStage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("failurestage");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("filename");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("filepath");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer")
                        .HasColumnName("maxretries");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("nextretryat");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolvedat");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retrycount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_failedprocessingqueue");

                    b.HasIndex("DownloadedFileId")
                        .HasDatabaseName("ix_failedprocessingqueue_downloadedfileid");

                    b.HasIndex("FailedAt")
                        .HasDatabaseName("ix_failedprocessingqueue_failedat");

                    b.HasIndex("NextRetryAt")
                        .HasDatabaseName("ix_failedprocessingqueue_nextretryat");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_failedprocessingqueue_status");

                    b.HasIndex("Status", "NextRetryAt")
                        .HasDatabaseName("ix_failedprocessingqueue_status_nextretryat");

                    b.ToTable("failedprocessingqueue");
                });

            modelBuilder.Entity("NickScanCentralImagingPortal.Core.Models.IngestionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("details");

                    b.Property<int>("DownloadedFileId")
                        .HasColumnType("integer")
                        .HasColumnName("downloadedfileid");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("endtime");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("errormessage");

                    b.Property<string>("ProcessType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("processtype");

                    b.Property<int?>("RecordsProcessed")
                        .HasColumnType("integer")
                        .HasColumnName("recordsprocessed");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starttime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_ingestionlogs");

                    b.HasIndex("DownloadedFileId")
                        .HasDatabaseName("ix_ingestionlogs_downloadedfileid");

                    b.HasIndex("ProcessType")
                        .HasDatabaseName("ix_ingestionlogs_processtype");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_ingestionlogs_status");

                    b.ToTable("ingestionlogs");
                });

            modelBuilder.Entity("NickScanCentralImagingPortal.Core.Models.VehicleImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BLNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("blnumber");

                    b.Property<int>("BOEDocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("boedocumentid");

                    b.Property<string>("ChassisNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("chassisnumber");

                    b.Property<string>("ClearanceType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("clearancetype");

                    b.Property<string>("ConsigneeName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("consigneename");

                    b.Property<string>("ContainerNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("containernumber");

                    b.Property<string>("CountryOfOrigin")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("countryoforigin");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CrmsLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("crmslevel");

                    b.Property<string>("DeclarationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("declarationnumber");

                    b.Property<decimal?>("DutyPaid")
                        .HasColumnType("numeric")
                        .HasColumnName("dutypaid");

                    b.Property<string>("EngineCapacity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("enginecapacity");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("errormessage");

                    b.Property<string>("FOBCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("fobcurrency");

                    b.Property<decimal?>("FOBValue")
                        .HasColumnType("numeric")
                        .HasColumnName("fobvalue");

                    b.Property<string>("HSCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("hscode");

                    b.Property<string>("HouseBL")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("housebl");

                    b.Property<int>("ImportType")
                        .HasColumnType("integer")
                        .HasColumnName("importtype");

                    b.Property<string>("ImporterName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("importername");

                    b.Property<string>("Make")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processedat");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("processingstatus");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Remarks")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("remarks");

                    b.Property<string>("RotationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rotationnumber");

                    b.Property<string>("ShipperName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("shippername");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("vin");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("vehicletype");

                    b.Property<string>("VehicleYear")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("vehicleyear");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_vehicleimports");

                    b.HasIndex("BOEDocumentId")
                        .HasDatabaseName("ix_vehicleimports_boedocumentid");

                    b.HasIndex("ChassisNumber")
                        .HasDatabaseName("ix_vehicleimports_chassisnumber");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_vehicleimports_createdat");

                    b.HasIndex("DeclarationNumber")
                        .HasDatabaseName("ix_vehicleimports_declarationnumber");

                    b.HasIndex("ImportType")
                        .HasDatabaseName("ix_vehicleimports_importtype");

                    b.HasIndex("ProcessingStatus")
                        .HasDatabaseName("ix_vehicleimports_processingstatus");

                    b.HasIndex("VIN")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicleimports_vin");

                    b.ToTable("vehicleimports");
                });

            modelBuilder.Entity("NickScanCentralImagingPortal.Core.Models.BOEDocument", b =>
                {
                    b.HasOne("NickScanCentralImagingPortal.Core.Models.DownloadedFile", "DownloadedFile")
                        .WithMany()
                        .HasForeignKey("DownloadedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_boedocuments_downloadedfiles_downloadedfileid");

                    b.Navigation("DownloadedFile");
                });

            modelBuilder.Entity("NickScanCentralImagingPortal.Core.Models.DownloadedManifestItem", b =>
                {
                    b.HasOne("NickScanCentralImagingPortal.Core.Models.BOEDocument", "BOEDocument")
                        .WithMany()
                        .HasForeignKey("BOEDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_manifestitems_boedocuments_boedocumentid");

                    b.Navigation("BOEDocument");
                });

            modelBuilder.Entity("NickScanCentralImagingPortal.Core.Models.IngestionLog", b =>
                {
                    b.HasOne("NickScanCentralImagingPortal.Core.Models.DownloadedFile", "DownloadedFile")
                        .WithMany()
                        .HasForeignKey("DownloadedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingestionlogs_downloadedfiles_downloadedfileid");

                    b.Navigation("DownloadedFile");
                });

            modelBuilder.Entity("NickScanCentralImagingPortal.Core.Models.VehicleImport", b =>
                {
                    b.HasOne("NickScanCentralImagingPortal.Core.Models.BOEDocument", "BOEDocument")
                        .WithMany()
                        .HasForeignKey("BOEDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicleimports_boedocuments_boedocumentid");

                    b.Navigation("BOEDocument");
                });
#pragma warning restore 612, 618
        }
    }
}
