// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NickFinance.AR;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NickFinance.AR.Migrations
{
    [DbContext(typeof(ArDbContext))]
    [Migration("20260426121830_Initial_Ar")]
    partial class Initial_Ar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ar")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NickFinance.AR.ArInvoice", b =>
                {
                    b.Property<Guid>("ArInvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("EvatIrn")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("evat_irn");

                    b.Property<DateTimeOffset?>("EvatIssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evat_issued_at");

                    b.Property<long>("GrossMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("gross_minor");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("invoice_no");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid?>("LedgerEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_event_id");

                    b.Property<long>("LeviesMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("levies_minor");

                    b.Property<long>("PaidMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("paid_minor");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference");

                    b.Property<string>("SourceEntityId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_entity_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_module");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<long>("SubtotalNetMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("subtotal_net_minor");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<long>("VatMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("vat_minor");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("void_reason");

                    b.Property<DateTimeOffset?>("VoidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at");

                    b.HasKey("ArInvoiceId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TenantId", "InvoiceNo")
                        .IsUnique()
                        .HasDatabaseName("ux_invoices_tenant_invoiceno");

                    b.HasIndex("TenantId", "CustomerId", "Status")
                        .HasDatabaseName("ix_invoices_tenant_customer_status");

                    b.ToTable("invoices", "ar");
                });

            modelBuilder.Entity("NickFinance.AR.ArInvoiceLine", b =>
                {
                    b.Property<Guid>("ArInvoiceLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_line_id");

                    b.Property<Guid>("ArInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<short>("LineNo")
                        .HasColumnType("smallint")
                        .HasColumnName("line_no");

                    b.Property<long>("NetAmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("net_amount_minor");

                    b.Property<string>("RevenueAccount")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("revenue_account");

                    b.HasKey("ArInvoiceLineId");

                    b.HasIndex("ArInvoiceId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("ux_invoice_lines_invoice_line");

                    b.ToTable("invoice_lines", "ar");
                });

            modelBuilder.Entity("NickFinance.AR.ArReceipt", b =>
                {
                    b.Property<Guid>("ArReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<Guid>("ArInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("CashAccount")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cash_account");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<Guid?>("LedgerEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_event_id");

                    b.Property<DateOnly>("ReceiptDate")
                        .HasColumnType("date")
                        .HasColumnName("receipt_date");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("ArReceiptId");

                    b.HasIndex("ArInvoiceId");

                    b.HasIndex("TenantId", "ArInvoiceId", "ReceiptDate")
                        .HasDatabaseName("ix_receipts_tenant_invoice_date");

                    b.ToTable("receipts", "ar");
                });

            modelBuilder.Entity("NickFinance.AR.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("ArControlAccount")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ar_control_account");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsVatRegistered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_vat_registered");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tin")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tin");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CustomerId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_customers_tenant_code");

                    b.ToTable("customers", "ar");
                });

            modelBuilder.Entity("NickFinance.AR.ArInvoice", b =>
                {
                    b.HasOne("NickFinance.AR.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NickFinance.AR.ArInvoiceLine", b =>
                {
                    b.HasOne("NickFinance.AR.ArInvoice", null)
                        .WithMany("Lines")
                        .HasForeignKey("ArInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NickFinance.AR.ArReceipt", b =>
                {
                    b.HasOne("NickFinance.AR.ArInvoice", null)
                        .WithMany()
                        .HasForeignKey("ArInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NickFinance.AR.ArInvoice", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
