-- =============================================================================
-- NICKSCAN ERP SOLUTION - Phase 1 - Add tenant_id to nickscan_production
-- Generated by tools/migrations/phase1-tenancy/generate-tenant-migrations.ps1
-- Run as: psql -h localhost -U postgres -d nickscan_production -f 10-nickscan-production-add-tenant-id.sql
-- =============================================================================
BEGIN;
SET LOCAL search_path = public;

-- aidatasetsnapshots
ALTER TABLE "aidatasetsnapshots" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_aidatasetsnapshots_tenant_id" ON "aidatasetsnapshots" (tenant_id, "id");

-- aiimageanalysissuggestions
ALTER TABLE "aiimageanalysissuggestions" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_aiimageanalysissuggestions_tenant_id" ON "aiimageanalysissuggestions" (tenant_id, "id");

-- analysisassignments
ALTER TABLE "analysisassignments" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_analysisassignments_tenant_id" ON "analysisassignments" (tenant_id, "id");

-- analysisgroups
ALTER TABLE "analysisgroups" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_analysisgroups_tenant_id" ON "analysisgroups" (tenant_id, "id");

-- analysisparentgroups
ALTER TABLE "analysisparentgroups" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_analysisparentgroups_tenant_id" ON "analysisparentgroups" (tenant_id, "id");

-- analysisrecords
ALTER TABLE "analysisrecords" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_analysisrecords_tenant_id" ON "analysisrecords" (tenant_id, "id");

-- analysissettings
ALTER TABLE "analysissettings" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_analysissettings_tenant_id" ON "analysissettings" (tenant_id, "id");

-- analysissubmissions
ALTER TABLE "analysissubmissions" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_analysissubmissions_tenant_id" ON "analysissubmissions" (tenant_id, "id");

-- applicationlogs
ALTER TABLE "applicationlogs" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_applicationlogs_tenant_id" ON "applicationlogs" (tenant_id, "id");

-- asescans
ALTER TABLE "asescans" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_asescans_tenant_id" ON "asescans" (tenant_id, "id");

-- asesynclogs
ALTER TABLE "asesynclogs" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_asesynclogs_tenant_id" ON "asesynclogs" (tenant_id, "id");

-- attendancerecords
ALTER TABLE "attendancerecords" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_attendancerecords_tenant_id" ON "attendancerecords" (tenant_id, "id");

-- auditdecisions
ALTER TABLE "auditdecisions" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_auditdecisions_tenant_id" ON "auditdecisions" (tenant_id, "id");

-- auditlogs
ALTER TABLE "auditlogs" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_auditlogs_tenant_id" ON "auditlogs" (tenant_id, "id");

-- blreviewrecords
ALTER TABLE "blreviewrecords" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_blreviewrecords_tenant_id" ON "blreviewrecords" (tenant_id, "id");

-- businessrules
ALTER TABLE "businessrules" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_businessrules_tenant_id" ON "businessrules" (tenant_id, "id");

-- containerannotations
ALTER TABLE "containerannotations" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_containerannotations_tenant_id" ON "containerannotations" (tenant_id, "id");

-- containerboerelations
ALTER TABLE "containerboerelations" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_containerboerelations_tenant_id" ON "containerboerelations" (tenant_id, "id");

-- containercompletenessstatuses
ALTER TABLE "containercompletenessstatuses" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_containercompletenessstatuses_tenant_id" ON "containercompletenessstatuses" (tenant_id, "id");

-- containerimages
ALTER TABLE "containerimages" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_containerimages_tenant_id" ON "containerimages" (tenant_id, "id");

-- containerreviewdecisions
ALTER TABLE "containerreviewdecisions" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_containerreviewdecisions_tenant_id" ON "containerreviewdecisions" (tenant_id, "id");

-- containers
ALTER TABLE "containers" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_containers_tenant_id" ON "containers" (tenant_id, "id");

-- containerscanqueues
ALTER TABLE "containerscanqueues" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_containerscanqueues_tenant_id" ON "containerscanqueues" (tenant_id, "id");

-- crossrecordscans
ALTER TABLE "crossrecordscans" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_crossrecordscans_tenant_id" ON "crossrecordscans" (tenant_id, "id");

-- decisionagentauditlogs
ALTER TABLE "decisionagentauditlogs" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_decisionagentauditlogs_tenant_id" ON "decisionagentauditlogs" (tenant_id, "id");

-- decisionagentconditions
ALTER TABLE "decisionagentconditions" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_decisionagentconditions_tenant_id" ON "decisionagentconditions" (tenant_id, "id");

-- decisionagentsettings
ALTER TABLE "decisionagentsettings" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_decisionagentsettings_tenant_id" ON "decisionagentsettings" (tenant_id, "id");

-- employeepositions
ALTER TABLE "employeepositions" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_employeepositions_tenant_id" ON "employeepositions" (tenant_id, "id");

-- employees
ALTER TABLE "employees" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_employees_tenant_id" ON "employees" (tenant_id, "id");

-- endpointusagelog
ALTER TABLE "endpointusagelog" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_endpointusagelog_tenant_id" ON "endpointusagelog" (tenant_id, "id");

-- errorinvestigations
ALTER TABLE "errorinvestigations" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_errorinvestigations_tenant_id" ON "errorinvestigations" (tenant_id, "id");

-- fixauditlogs
ALTER TABLE "fixauditlogs" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_fixauditlogs_tenant_id" ON "fixauditlogs" (tenant_id, "id");

-- fixproposals
ALTER TABLE "fixproposals" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_fixproposals_tenant_id" ON "fixproposals" (tenant_id, "id");

-- fs6000fileprocessings
ALTER TABLE "fs6000fileprocessings" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_fs6000fileprocessings_tenant_id" ON "fs6000fileprocessings" (tenant_id, "id");

-- fs6000images
ALTER TABLE "fs6000images" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_fs6000images_tenant_id" ON "fs6000images" (tenant_id, "id");

-- fs6000scans
ALTER TABLE "fs6000scans" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_fs6000scans_tenant_id" ON "fs6000scans" (tenant_id, "id");

-- fs6000synclogs
ALTER TABLE "fs6000synclogs" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_fs6000synclogs_tenant_id" ON "fs6000synclogs" (tenant_id, "id");

-- heimannsmithscannerdata
ALTER TABLE "heimannsmithscannerdata" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_heimannsmithscannerdata_tenant_id" ON "heimannsmithscannerdata" (tenant_id, "id");

-- icumcontainerdata
ALTER TABLE "icumcontainerdata" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_icumcontainerdata_tenant_id" ON "icumcontainerdata" (tenant_id, "id");

-- icummanifestitems
ALTER TABLE "icummanifestitems" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_icummanifestitems_tenant_id" ON "icummanifestitems" (tenant_id, "id");

-- icumsdownloadqueues
ALTER TABLE "icumsdownloadqueues" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_icumsdownloadqueues_tenant_id" ON "icumsdownloadqueues" (tenant_id, "id");

-- icumssubmissionqueues
ALTER TABLE "icumssubmissionqueues" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_icumssubmissionqueues_tenant_id" ON "icumssubmissionqueues" (tenant_id, "id");

-- image_split_assignments
ALTER TABLE "image_split_assignments" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_image_split_assignments_tenant_id" ON "image_split_assignments" (tenant_id, "id");

-- image_split_jobs
ALTER TABLE "image_split_jobs" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_image_split_jobs_tenant_id" ON "image_split_jobs" (tenant_id, "id");

-- image_split_results
ALTER TABLE "image_split_results" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_image_split_results_tenant_id" ON "image_split_results" (tenant_id, "id");

-- imageanalysisdecisions
ALTER TABLE "imageanalysisdecisions" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_imageanalysisdecisions_tenant_id" ON "imageanalysisdecisions" (tenant_id, "id");

-- imagecaches
ALTER TABLE "imagecaches" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_imagecaches_tenant_id" ON "imagecaches" (tenant_id, "id");

-- lanes
ALTER TABLE "lanes" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_lanes_tenant_id" ON "lanes" (tenant_id, "id");

-- leaverequests
ALTER TABLE "leaverequests" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_leaverequests_tenant_id" ON "leaverequests" (tenant_id, "id");

-- manualboerequests
ALTER TABLE "manualboerequests" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_manualboerequests_tenant_id" ON "manualboerequests" (tenant_id, "id");

-- notifications
ALTER TABLE "notifications" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_notifications_tenant_id" ON "notifications" (tenant_id, "id");

-- nuctechscannerdata
ALTER TABLE "nuctechscannerdata" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_nuctechscannerdata_tenant_id" ON "nuctechscannerdata" (tenant_id, "id");

-- organizations
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_organizations_tenant_id" ON "organizations" (tenant_id, "id");

-- orgunits
ALTER TABLE "orgunits" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_orgunits_tenant_id" ON "orgunits" (tenant_id, "id");

-- originalscanrecords
ALTER TABLE "originalscanrecords" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_originalscanrecords_tenant_id" ON "originalscanrecords" (tenant_id, "id");

-- permissionauditlogs
ALTER TABLE "permissionauditlogs" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_permissionauditlogs_tenant_id" ON "permissionauditlogs" (tenant_id, "id");

-- permissions
ALTER TABLE "permissions" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_permissions_tenant_id" ON "permissions" (tenant_id, "id");

-- positions
ALTER TABLE "positions" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_positions_tenant_id" ON "positions" (tenant_id, "id");

-- processingresults
ALTER TABLE "processingresults" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_processingresults_tenant_id" ON "processingresults" (tenant_id, "id");

-- rolepermissions
ALTER TABLE "rolepermissions" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_rolepermissions_tenant_id" ON "rolepermissions" (tenant_id, "id");

-- roles
ALTER TABLE "roles" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_roles_tenant_id" ON "roles" (tenant_id, "id");

-- scannerassets
ALTER TABLE "scannerassets" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_scannerassets_tenant_id" ON "scannerassets" (tenant_id, "id");

-- settingshistory
ALTER TABLE "settingshistory" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_settingshistory_tenant_id" ON "settingshistory" (tenant_id, "id");

-- shiftassignments
ALTER TABLE "shiftassignments" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_shiftassignments_tenant_id" ON "shiftassignments" (tenant_id, "id");

-- shiftcoveragerequirements
ALTER TABLE "shiftcoveragerequirements" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_shiftcoveragerequirements_tenant_id" ON "shiftcoveragerequirements" (tenant_id, "id");

-- shiftswaprequests
ALTER TABLE "shiftswaprequests" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_shiftswaprequests_tenant_id" ON "shiftswaprequests" (tenant_id, "id");

-- shifttemplates
ALTER TABLE "shifttemplates" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_shifttemplates_tenant_id" ON "shifttemplates" (tenant_id, "id");

-- sites
ALTER TABLE "sites" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_sites_tenant_id" ON "sites" (tenant_id, "id");

-- systemsettings
ALTER TABLE "systemsettings" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_systemsettings_tenant_id" ON "systemsettings" (tenant_id, "id");

-- userpermissions
ALTER TABLE "userpermissions" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_userpermissions_tenant_id" ON "userpermissions" (tenant_id, "id");

-- userpreferences
ALTER TABLE "userpreferences" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_userpreferences_tenant_id" ON "userpreferences" (tenant_id, "id");

-- userreadiness
ALTER TABLE "userreadiness" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_userreadiness_tenant_id" ON "userreadiness" (tenant_id, "id");

-- users
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_users_tenant_id" ON "users" (tenant_id, "id");

-- wavependingcontainers
ALTER TABLE "wavependingcontainers" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_wavependingcontainers_tenant_id" ON "wavependingcontainers" (tenant_id, "id");

COMMIT;
