-- =============================================================================
-- NICKSCAN ERP SOLUTION - Phase 1 - Add tenant_id to nickhr
-- Generated by tools/migrations/phase1-tenancy/generate-tenant-migrations.ps1
-- Run as: psql -h localhost -U postgres -d nickhr -f 11-nickhr-add-tenant-id.sql
-- =============================================================================
BEGIN;
SET LOCAL search_path = public;

-- AchievementEntries
ALTER TABLE "AchievementEntries" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_achievemententries_tenant_id" ON "AchievementEntries" (tenant_id, "Id");

-- Announcements
ALTER TABLE "Announcements" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_announcements_tenant_id" ON "Announcements" (tenant_id, "Id");

-- Applications
ALTER TABLE "Applications" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_applications_tenant_id" ON "Applications" (tenant_id, "Id");

-- AppraisalCycles
ALTER TABLE "AppraisalCycles" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_appraisalcycles_tenant_id" ON "AppraisalCycles" (tenant_id, "Id");

-- AppraisalForms
ALTER TABLE "AppraisalForms" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_appraisalforms_tenant_id" ON "AppraisalForms" (tenant_id, "Id");

-- ApprovalDelegations
ALTER TABLE "ApprovalDelegations" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_approvaldelegations_tenant_id" ON "ApprovalDelegations" (tenant_id, "Id");

-- Approvals
ALTER TABLE "Approvals" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_approvals_tenant_id" ON "Approvals" (tenant_id, "Id");

-- AssetAssignments
ALTER TABLE "AssetAssignments" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_assetassignments_tenant_id" ON "AssetAssignments" (tenant_id, "Id");

-- Assets
ALTER TABLE "Assets" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_assets_tenant_id" ON "Assets" (tenant_id, "Id");

-- AttendanceRecords
ALTER TABLE "AttendanceRecords" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_attendancerecords_tenant_id" ON "AttendanceRecords" (tenant_id, "Id");

-- AuditLogs
ALTER TABLE "AuditLogs" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_auditlogs_tenant_id" ON "AuditLogs" (tenant_id, "Id");

-- Beneficiaries
ALTER TABLE "Beneficiaries" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_beneficiaries_tenant_id" ON "Beneficiaries" (tenant_id, "Id");

-- Candidates
ALTER TABLE "Candidates" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_candidates_tenant_id" ON "Candidates" (tenant_id, "Id");

-- ClearanceItems
ALTER TABLE "ClearanceItems" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_clearanceitems_tenant_id" ON "ClearanceItems" (tenant_id, "Id");

-- CompanySettings
ALTER TABLE "CompanySettings" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_companysettings_tenant_id" ON "CompanySettings" (tenant_id, "Id");

-- Competencies
ALTER TABLE "Competencies" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_competencies_tenant_id" ON "Competencies" (tenant_id, "Id");

-- CompetencyFrameworks
ALTER TABLE "CompetencyFrameworks" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_competencyframeworks_tenant_id" ON "CompetencyFrameworks" (tenant_id, "Id");

-- ComplianceDeadlines
ALTER TABLE "ComplianceDeadlines" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_compliancedeadlines_tenant_id" ON "ComplianceDeadlines" (tenant_id, "Id");

-- Departments
ALTER TABLE "Departments" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_departments_tenant_id" ON "Departments" (tenant_id, "Id");

-- Dependents
ALTER TABLE "Dependents" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_dependents_tenant_id" ON "Dependents" (tenant_id, "Id");

-- Designations
ALTER TABLE "Designations" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_designations_tenant_id" ON "Designations" (tenant_id, "Id");

-- DisciplinaryCases
ALTER TABLE "DisciplinaryCases" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_disciplinarycases_tenant_id" ON "DisciplinaryCases" (tenant_id, "Id");

-- EmailTemplates
ALTER TABLE "EmailTemplates" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_emailtemplates_tenant_id" ON "EmailTemplates" (tenant_id, "Id");

-- EmergencyContacts
ALTER TABLE "EmergencyContacts" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_emergencycontacts_tenant_id" ON "EmergencyContacts" (tenant_id, "Id");

-- EmployeeDocuments
ALTER TABLE "EmployeeDocuments" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_employeedocuments_tenant_id" ON "EmployeeDocuments" (tenant_id, "Id");

-- EmployeeQualifications
ALTER TABLE "EmployeeQualifications" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_employeequalifications_tenant_id" ON "EmployeeQualifications" (tenant_id, "Id");

-- EmployeeSalaryStructures
ALTER TABLE "EmployeeSalaryStructures" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_employeesalarystructures_tenant_id" ON "EmployeeSalaryStructures" (tenant_id, "Id");

-- EmployeeSkills
ALTER TABLE "EmployeeSkills" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_employeeskills_tenant_id" ON "EmployeeSkills" (tenant_id, "Id");

-- Employees
ALTER TABLE "Employees" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_employees_tenant_id" ON "Employees" (tenant_id, "Id");

-- EmployeesOfMonth
ALTER TABLE "EmployeesOfMonth" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_employeesofmonth_tenant_id" ON "EmployeesOfMonth" (tenant_id, "Id");

-- EmploymentHistoryRecords
ALTER TABLE "EmploymentHistoryRecords" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_employmenthistoryrecords_tenant_id" ON "EmploymentHistoryRecords" (tenant_id, "Id");

-- ExcuseDuties
ALTER TABLE "ExcuseDuties" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_excuseduties_tenant_id" ON "ExcuseDuties" (tenant_id, "Id");

-- ExitInterviews
ALTER TABLE "ExitInterviews" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_exitinterviews_tenant_id" ON "ExitInterviews" (tenant_id, "Id");

-- ExpenseClaims
ALTER TABLE "ExpenseClaims" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_expenseclaims_tenant_id" ON "ExpenseClaims" (tenant_id, "Id");

-- FinalSettlements
ALTER TABLE "FinalSettlements" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_finalsettlements_tenant_id" ON "FinalSettlements" (tenant_id, "Id");

-- GeneratedLetters
ALTER TABLE "GeneratedLetters" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_generatedletters_tenant_id" ON "GeneratedLetters" (tenant_id, "Id");

-- Goals
ALTER TABLE "Goals" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_goals_tenant_id" ON "Goals" (tenant_id, "Id");

-- Grades
ALTER TABLE "Grades" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_grades_tenant_id" ON "Grades" (tenant_id, "Id");

-- Grievances
ALTER TABLE "Grievances" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_grievances_tenant_id" ON "Grievances" (tenant_id, "Id");

-- Holidays
ALTER TABLE "Holidays" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_holidays_tenant_id" ON "Holidays" (tenant_id, "Id");

-- Interviews
ALTER TABLE "Interviews" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_interviews_tenant_id" ON "Interviews" (tenant_id, "Id");

-- JobPostings
ALTER TABLE "JobPostings" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_jobpostings_tenant_id" ON "JobPostings" (tenant_id, "Id");

-- JobRequisitions
ALTER TABLE "JobRequisitions" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_jobrequisitions_tenant_id" ON "JobRequisitions" (tenant_id, "Id");

-- LeaveBalances
ALTER TABLE "LeaveBalances" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_leavebalances_tenant_id" ON "LeaveBalances" (tenant_id, "Id");

-- LeavePolicies
ALTER TABLE "LeavePolicies" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_leavepolicies_tenant_id" ON "LeavePolicies" (tenant_id, "Id");

-- LeaveRequests
ALTER TABLE "LeaveRequests" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_leaverequests_tenant_id" ON "LeaveRequests" (tenant_id, "Id");

-- LetterTemplates
ALTER TABLE "LetterTemplates" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_lettertemplates_tenant_id" ON "LetterTemplates" (tenant_id, "Id");

-- LoanApplications
ALTER TABLE "LoanApplications" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_loanapplications_tenant_id" ON "LoanApplications" (tenant_id, "Id");

-- LoanRepayments
ALTER TABLE "LoanRepayments" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_loanrepayments_tenant_id" ON "LoanRepayments" (tenant_id, "Id");

-- Loans
ALTER TABLE "Loans" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_loans_tenant_id" ON "Loans" (tenant_id, "Id");

-- Locations
ALTER TABLE "Locations" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_locations_tenant_id" ON "Locations" (tenant_id, "Id");

-- LoginAudits
ALTER TABLE "LoginAudits" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_loginaudits_tenant_id" ON "LoginAudits" (tenant_id, "Id");

-- MedicalBenefits
ALTER TABLE "MedicalBenefits" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_medicalbenefits_tenant_id" ON "MedicalBenefits" (tenant_id, "Id");

-- MedicalClaims
ALTER TABLE "MedicalClaims" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_medicalclaims_tenant_id" ON "MedicalClaims" (tenant_id, "Id");

-- Notifications
ALTER TABLE "Notifications" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_notifications_tenant_id" ON "Notifications" (tenant_id, "Id");

-- OfferLetters
ALTER TABLE "OfferLetters" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_offerletters_tenant_id" ON "OfferLetters" (tenant_id, "Id");

-- OneOnOneMeetings
ALTER TABLE "OneOnOneMeetings" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_oneononemeetings_tenant_id" ON "OneOnOneMeetings" (tenant_id, "Id");

-- OutOfStationRates
ALTER TABLE "OutOfStationRates" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_outofstationrates_tenant_id" ON "OutOfStationRates" (tenant_id, "Id");

-- OutOfStationRequests
ALTER TABLE "OutOfStationRequests" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_outofstationrequests_tenant_id" ON "OutOfStationRequests" (tenant_id, "Id");

-- OvertimeRequests
ALTER TABLE "OvertimeRequests" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_overtimerequests_tenant_id" ON "OvertimeRequests" (tenant_id, "Id");

-- PayrollItemDetails
ALTER TABLE "PayrollItemDetails" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_payrollitemdetails_tenant_id" ON "PayrollItemDetails" (tenant_id, "Id");

-- PayrollItems
ALTER TABLE "PayrollItems" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_payrollitems_tenant_id" ON "PayrollItems" (tenant_id, "Id");

-- PayrollRuns
ALTER TABLE "PayrollRuns" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_payrollruns_tenant_id" ON "PayrollRuns" (tenant_id, "Id");

-- PolicyAcknowledgements
ALTER TABLE "PolicyAcknowledgements" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_policyacknowledgements_tenant_id" ON "PolicyAcknowledgements" (tenant_id, "Id");

-- PolicyDocuments
ALTER TABLE "PolicyDocuments" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_policydocuments_tenant_id" ON "PolicyDocuments" (tenant_id, "Id");

-- ProbationReviews
ALTER TABLE "ProbationReviews" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_probationreviews_tenant_id" ON "ProbationReviews" (tenant_id, "Id");

-- ProfileChangeRequests
ALTER TABLE "ProfileChangeRequests" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_profilechangerequests_tenant_id" ON "ProfileChangeRequests" (tenant_id, "Id");

-- Projects
ALTER TABLE "Projects" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_projects_tenant_id" ON "Projects" (tenant_id, "Id");

-- Recognitions
ALTER TABLE "Recognitions" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_recognitions_tenant_id" ON "Recognitions" (tenant_id, "Id");

-- RoleClaims
ALTER TABLE "RoleClaims" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_roleclaims_tenant_id" ON "RoleClaims" (tenant_id, "Id");

-- Roles
ALTER TABLE "Roles" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_roles_tenant_id" ON "Roles" (tenant_id, "Id");

-- SalaryComponents
ALTER TABLE "SalaryComponents" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_salarycomponents_tenant_id" ON "SalaryComponents" (tenant_id, "Id");

-- Separations
ALTER TABLE "Separations" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_separations_tenant_id" ON "Separations" (tenant_id, "Id");

-- ShiftAssignments
ALTER TABLE "ShiftAssignments" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_shiftassignments_tenant_id" ON "ShiftAssignments" (tenant_id, "Id");

-- Shifts
ALTER TABLE "Shifts" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_shifts_tenant_id" ON "Shifts" (tenant_id, "Id");

-- Skills
ALTER TABLE "Skills" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_skills_tenant_id" ON "Skills" (tenant_id, "Id");

-- SuccessionCandidates
ALTER TABLE "SuccessionCandidates" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_successioncandidates_tenant_id" ON "SuccessionCandidates" (tenant_id, "Id");

-- SuccessionPlans
ALTER TABLE "SuccessionPlans" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_successionplans_tenant_id" ON "SuccessionPlans" (tenant_id, "Id");

-- SurveyAnswers
ALTER TABLE "SurveyAnswers" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_surveyanswers_tenant_id" ON "SurveyAnswers" (tenant_id, "Id");

-- SurveyQuestions
ALTER TABLE "SurveyQuestions" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_surveyquestions_tenant_id" ON "SurveyQuestions" (tenant_id, "Id");

-- SurveyResponses
ALTER TABLE "SurveyResponses" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_surveyresponses_tenant_id" ON "SurveyResponses" (tenant_id, "Id");

-- Surveys
ALTER TABLE "Surveys" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_surveys_tenant_id" ON "Surveys" (tenant_id, "Id");

-- TimesheetEntries
ALTER TABLE "TimesheetEntries" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_timesheetentries_tenant_id" ON "TimesheetEntries" (tenant_id, "Id");

-- TrainingAttendances
ALTER TABLE "TrainingAttendances" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_trainingattendances_tenant_id" ON "TrainingAttendances" (tenant_id, "Id");

-- TrainingPrograms
ALTER TABLE "TrainingPrograms" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_trainingprograms_tenant_id" ON "TrainingPrograms" (tenant_id, "Id");

-- TransferPromotions
ALTER TABLE "TransferPromotions" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_transferpromotions_tenant_id" ON "TransferPromotions" (tenant_id, "Id");

-- TravelRequests
ALTER TABLE "TravelRequests" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_travelrequests_tenant_id" ON "TravelRequests" (tenant_id, "Id");

-- UserClaims
ALTER TABLE "UserClaims" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_userclaims_tenant_id" ON "UserClaims" (tenant_id, "Id");

-- UserLogins
ALTER TABLE "UserLogins" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_userlogins_tenant_id" ON "UserLogins" (tenant_id, "LoginProvider");

-- UserRoles
ALTER TABLE "UserRoles" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_userroles_tenant_id" ON "UserRoles" (tenant_id, "UserId");

-- UserSystemAccesses
ALTER TABLE "UserSystemAccesses" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_usersystemaccesses_tenant_id" ON "UserSystemAccesses" (tenant_id, "Id");

-- UserTokens
ALTER TABLE "UserTokens" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_usertokens_tenant_id" ON "UserTokens" (tenant_id, "UserId");

-- Users
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_users_tenant_id" ON "Users" (tenant_id, "Id");

-- Warnings
ALTER TABLE "Warnings" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_warnings_tenant_id" ON "Warnings" (tenant_id, "Id");

-- WorkflowSteps
ALTER TABLE "WorkflowSteps" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_workflowsteps_tenant_id" ON "WorkflowSteps" (tenant_id, "Id");

-- Workflows
ALTER TABLE "Workflows" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_workflows_tenant_id" ON "Workflows" (tenant_id, "Id");

COMMIT;
