-- =============================================================================
-- NICKSCAN ERP SOLUTION - Phase 1 - Add tenant_id to nick_comms
-- Generated by tools/migrations/phase1-tenancy/generate-tenant-migrations.ps1
-- Run as: psql -h localhost -U postgres -d nick_comms -f 12-nick-comms-add-tenant-id.sql
-- =============================================================================
BEGIN;
SET LOCAL search_path = public;

-- api_keys
ALTER TABLE "api_keys" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_api_keys_tenant_id" ON "api_keys" (tenant_id, "id");

-- email_messages
ALTER TABLE "email_messages" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_email_messages_tenant_id" ON "email_messages" (tenant_id, "id");

-- otp_sessions
ALTER TABLE "otp_sessions" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_otp_sessions_tenant_id" ON "otp_sessions" (tenant_id, "id");

-- sms_messages
ALTER TABLE "sms_messages" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS "ix_sms_messages_tenant_id" ON "sms_messages" (tenant_id, "id");

COMMIT;
