# =============================================================================
# NICKSCAN ERP SOLUTION — Phase 1 — SQL Migration Generator
#
# Queries each module database for its public tables and emits:
#   - 1{n}-{db}-add-tenant-id.sql  (ADD COLUMN tenant_id, ADD INDEX)
#   - 2{n}-{db}-rls.sql            (ENABLE RLS + per-table policy)
#
# Re-run this script if any module's schema changes before the live migration.
# =============================================================================

param(
    [string]$DbHost = "localhost",
    [int]$Port = 5432,
    [string]$User = "postgres"
)

$ErrorActionPreference = "Stop"
$psql = "C:\Program Files\PostgreSQL\18\bin\psql.exe"
$outDir = $PSScriptRoot
$env:PGPASSWORD = $env:NICKSCAN_DB_PASSWORD
if (-not $env:PGPASSWORD) {
    Write-Error "Set NICKSCAN_DB_PASSWORD env var first."
    exit 1
}

$databases = @(
    @{ Name = "nickscan_production"; AddPrefix = "10-nickscan-production"; RlsPrefix = "20-nickscan-production"; Slug = "nickscan_production" }
    @{ Name = "nickhr";              AddPrefix = "11-nickhr";              RlsPrefix = "21-nickhr";              Slug = "nickhr" }
    @{ Name = "nick_comms";          AddPrefix = "12-nick-comms";          RlsPrefix = "22-nick-comms";          Slug = "nick_comms" }
)

function Get-TablesAndPks {
    param([string]$Db)
    $sql = @"
SELECT t.table_name,
       (SELECT a.attname
        FROM pg_index i
        JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
        WHERE i.indrelid = (quote_ident(t.table_name))::regclass
          AND i.indisprimary
        LIMIT 1) AS pk_column
FROM information_schema.tables t
WHERE t.table_schema = 'public'
  AND t.table_type = 'BASE TABLE'
  AND t.table_name <> '__EFMigrationsHistory'
ORDER BY t.table_name;
"@
    & $psql -h $DbHost -p $Port -U $User -d $Db -tAF '|' -c $sql
}

function Write-AddTenantIdSql {
    param([string]$Db, [string]$Path, [object[]]$Rows)

    $sb = [System.Text.StringBuilder]::new()
    $null = $sb.AppendLine("-- =============================================================================")
    $null = $sb.AppendLine("-- NICKSCAN ERP SOLUTION - Phase 1 - Add tenant_id to $Db")
    $null = $sb.AppendLine("-- Generated by tools/migrations/phase1-tenancy/generate-tenant-migrations.ps1")
    $null = $sb.AppendLine("-- Run as: psql -h localhost -U postgres -d $Db -f $(Split-Path $Path -Leaf)")
    $null = $sb.AppendLine("-- =============================================================================")
    $null = $sb.AppendLine("BEGIN;")
    $null = $sb.AppendLine("SET LOCAL search_path = public;")
    $null = $sb.AppendLine("")

    foreach ($r in $Rows) {
        $tbl, $pk = $r -split '\|', 2
        if (-not $tbl) { continue }
        $idxName = "ix_${tbl}_tenant_id".ToLower()
        $null = $sb.AppendLine("-- $tbl")
        $null = $sb.AppendLine("ALTER TABLE `"$tbl`" ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;")
        if ($pk) {
            $null = $sb.AppendLine("CREATE INDEX IF NOT EXISTS `"$idxName`" ON `"$tbl`" (tenant_id, `"$pk`");")
        }
        else {
            $null = $sb.AppendLine("CREATE INDEX IF NOT EXISTS `"$idxName`" ON `"$tbl`" (tenant_id);")
        }
        $null = $sb.AppendLine("")
    }

    $null = $sb.AppendLine("COMMIT;")
    [System.IO.File]::WriteAllText($Path, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
}

function Write-RlsSql {
    param([string]$Db, [string]$Path, [object[]]$Rows, [int]$Number)

    $sb = [System.Text.StringBuilder]::new()
    $null = $sb.AppendLine("-- =============================================================================")
    $null = $sb.AppendLine("-- NICKSCAN ERP SOLUTION - Phase 1 - Enable Row-Level Security on $Db")
    $null = $sb.AppendLine("-- ")
    $null = $sb.AppendLine("-- Each table gets a policy that filters by current_setting('app.tenant_id').")
    $null = $sb.AppendLine("-- The TenantOwnedEntityInterceptor sets this session variable on every")
    $null = $sb.AppendLine("-- connection. Bypass for the postgres superuser via the BYPASSRLS attribute")
    $null = $sb.AppendLine("-- (already on by default for postgres role).")
    $null = $sb.AppendLine("-- =============================================================================")
    $null = $sb.AppendLine("BEGIN;")
    $null = $sb.AppendLine("SET LOCAL search_path = public;")
    $null = $sb.AppendLine("")

    foreach ($r in $Rows) {
        $tbl, $pk = $r -split '\|', 2
        if (-not $tbl) { continue }
        $polName = "tenant_isolation_$tbl".ToLower()
        $null = $sb.AppendLine("-- $tbl")
        $null = $sb.AppendLine("ALTER TABLE `"$tbl`" ENABLE ROW LEVEL SECURITY;")
        $null = $sb.AppendLine("DROP POLICY IF EXISTS `"$polName`" ON `"$tbl`";")
        $null = $sb.AppendLine("CREATE POLICY `"$polName`" ON `"$tbl`"")
        $null = $sb.AppendLine("    USING (tenant_id = COALESCE(NULLIF(current_setting('app.tenant_id', true), ''), '1')::bigint)")
        $null = $sb.AppendLine("    WITH CHECK (tenant_id = COALESCE(NULLIF(current_setting('app.tenant_id', true), ''), '1')::bigint);")
        $null = $sb.AppendLine("")
    }

    $null = $sb.AppendLine("COMMIT;")
    [System.IO.File]::WriteAllText($Path, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
}

foreach ($d in $databases) {
    Write-Host "Generating migrations for $($d.Name)..." -ForegroundColor Cyan
    $rows = Get-TablesAndPks -Db $d.Name
    if (-not $rows) { Write-Warning "  no tables found"; continue }
    $rowList = @($rows | Where-Object { $_ -and $_.Trim() })
    Write-Host "  found $($rowList.Count) tables" -ForegroundColor Gray

    $addPath = Join-Path $outDir "$($d.AddPrefix)-add-tenant-id.sql"
    $rlsPath = Join-Path $outDir "$($d.RlsPrefix)-rls.sql"

    Write-AddTenantIdSql -Db $d.Name -Path $addPath -Rows $rowList
    Write-RlsSql        -Db $d.Name -Path $rlsPath -Rows $rowList

    Write-Host "  -> $(Split-Path $addPath -Leaf)" -ForegroundColor Green
    Write-Host "  -> $(Split-Path $rlsPath -Leaf)" -ForegroundColor Green
}

Write-Host ""
Write-Host "Done. Review the generated .sql files before executing." -ForegroundColor Yellow
