// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NickFinance.Budgeting;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NickFinance.Budgeting.Migrations
{
    [DbContext(typeof(BudgetingDbContext))]
    [Migration("20260426175603_Initial_Budgeting")]
    partial class Initial_Budgeting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("budgeting")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NickFinance.Budgeting.AnnualBudget", b =>
                {
                    b.Property<Guid>("AnnualBudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("annual_budget_id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("department_code");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("AnnualBudgetId");

                    b.HasIndex("TenantId", "FiscalYear", "DepartmentCode")
                        .IsUnique()
                        .HasDatabaseName("ux_annual_budgets_tenant_year_dept");

                    b.ToTable("annual_budgets", "budgeting");
                });

            modelBuilder.Entity("NickFinance.Budgeting.BudgetLine", b =>
                {
                    b.Property<Guid>("BudgetLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("budget_line_id");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("account_code");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<Guid>("AnnualBudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("annual_budget_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<byte>("MonthNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("month_number");

                    b.HasKey("BudgetLineId");

                    b.HasIndex("AnnualBudgetId", "AccountCode", "MonthNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_budget_lines_budget_account_month");

                    b.ToTable("budget_lines", "budgeting");
                });

            modelBuilder.Entity("NickFinance.Budgeting.BudgetLine", b =>
                {
                    b.HasOne("NickFinance.Budgeting.AnnualBudget", null)
                        .WithMany("Lines")
                        .HasForeignKey("AnnualBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NickFinance.Budgeting.AnnualBudget", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
