// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NickScanCentralImagingPortal.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NickScanCentralImagingPortal.Infrastructure.Migrations.IcumDb
{
    [DbContext(typeof(IcumDbContext))]
    [Migration("20260318125806_InitialPostgreSql")]
    partial class InitialPostgreSql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NickScanCentralImagingPortal.Core.Models.IcumBatchLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enddate");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("errormessage");

                    b.Property<int>("RecordsProcessed")
                        .HasColumnType("integer")
                        .HasColumnName("recordsprocessed");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startdate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_icumbatchlogs");

                    b.ToTable("icumbatchlogs");
                });

            modelBuilder.Entity("NickScanCentralImagingPortal.Core.Models.IcumContainerData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BoeData")
                        .HasColumnType("text")
                        .HasColumnName("boedata");

                    b.Property<string>("ClearanceType")
                        .HasColumnType("text")
                        .HasColumnName("clearancetype");

                    b.Property<string>("ConsigneeName")
                        .HasColumnType("text")
                        .HasColumnName("consigneename");

                    b.Property<string>("ContainerISO")
                        .HasColumnType("text")
                        .HasColumnName("containeriso");

                    b.Property<string>("ContainerNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("containernumber");

                    b.Property<int?>("ContainerQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("containerquantity");

                    b.Property<decimal?>("ContainerWeight")
                        .HasColumnType("numeric")
                        .HasColumnName("containerweight");

                    b.Property<string>("CountryOfOrigin")
                        .HasColumnType("text")
                        .HasColumnName("countryoforigin");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CrmsLevel")
                        .HasColumnType("text")
                        .HasColumnName("crmslevel");

                    b.Property<string>("DeclarationNumber")
                        .HasColumnType("text")
                        .HasColumnName("declarationnumber");

                    b.Property<string>("HouseBl")
                        .HasColumnType("text")
                        .HasColumnName("housebl");

                    b.Property<string>("MasterBlNumber")
                        .HasColumnType("text")
                        .HasColumnName("masterblnumber");

                    b.Property<string>("RotationNumber")
                        .HasColumnType("text")
                        .HasColumnName("rotationnumber");

                    b.Property<string>("ShipperName")
                        .HasColumnType("text")
                        .HasColumnName("shippername");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalDutyPaid")
                        .HasColumnType("numeric")
                        .HasColumnName("totaldutypaid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_icumcontainerdata");

                    b.HasIndex("ClearanceType")
                        .HasDatabaseName("ix_icumcontainerdata_clearancetype");

                    b.HasIndex("ConsigneeName")
                        .HasDatabaseName("ix_icumcontainerdata_consigneename");

                    b.HasIndex("ContainerNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_icumcontainerdata_containernumber");

                    b.HasIndex("CountryOfOrigin")
                        .HasDatabaseName("ix_icumcontainerdata_countryoforigin");

                    b.HasIndex("CrmsLevel")
                        .HasDatabaseName("ix_icumcontainerdata_crmslevel");

                    b.HasIndex("DeclarationNumber")
                        .HasDatabaseName("ix_icumcontainerdata_declarationnumber");

                    b.HasIndex("HouseBl")
                        .HasDatabaseName("ix_icumcontainerdata_housebl");

                    b.HasIndex("MasterBlNumber")
                        .HasDatabaseName("ix_icumcontainerdata_masterblnumber");

                    b.HasIndex("RotationNumber")
                        .HasDatabaseName("ix_icumcontainerdata_rotationnumber");

                    b.HasIndex("ShipperName")
                        .HasDatabaseName("ix_icumcontainerdata_shippername");

                    b.ToTable("icumcontainerdata");
                });

            modelBuilder.Entity("NickScanCentralImagingPortal.Core.Models.IcumDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContainerNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("containernumber");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("DocumentData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("documentdata");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("documenttype");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_icumdocuments");

                    b.ToTable("icumdocuments");
                });

            modelBuilder.Entity("NickScanCentralImagingPortal.Core.Models.IcumManifestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryOfOrigin")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("countryoforigin");

                    b.Property<string>("Cpc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cpc");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("FobCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("fobcurrency");

                    b.Property<string>("HouseBl")
                        .HasColumnType("text")
                        .HasColumnName("housebl");

                    b.Property<string>("HsCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("hscode");

                    b.Property<int>("IcumContainerDataId")
                        .HasColumnType("integer")
                        .HasColumnName("icumcontainerdataid");

                    b.Property<decimal>("ItemDutyPaid")
                        .HasColumnType("numeric")
                        .HasColumnName("itemdutypaid");

                    b.Property<decimal>("ItemFob")
                        .HasColumnType("numeric")
                        .HasColumnName("itemfob");

                    b.Property<int>("ItemNo")
                        .HasColumnType("integer")
                        .HasColumnName("itemno");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_icummanifestitems");

                    b.HasIndex("CountryOfOrigin")
                        .HasDatabaseName("ix_icummanifestitems_countryoforigin");

                    b.HasIndex("HsCode")
                        .HasDatabaseName("ix_icummanifestitems_hscode");

                    b.HasIndex("IcumContainerDataId")
                        .HasDatabaseName("ix_icummanifestitems_icumcontainerdataid");

                    b.ToTable("icummanifestitems");
                });

            modelBuilder.Entity("NickScanCentralImagingPortal.Core.Models.IcumManifestItem", b =>
                {
                    b.HasOne("NickScanCentralImagingPortal.Core.Models.IcumContainerData", "IcumContainerData")
                        .WithMany("ManifestItems")
                        .HasForeignKey("IcumContainerDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_icummanifestitems_icumcontainerdata_icumcontainerdataid");

                    b.Navigation("IcumContainerData");
                });

            modelBuilder.Entity("NickScanCentralImagingPortal.Core.Models.IcumContainerData", b =>
                {
                    b.Navigation("ManifestItems");
                });
#pragma warning restore 612, 618
        }
    }
}
